---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: actualbudget-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: actualbudget
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 5006
      targetPort: 5006
  selector:
    app: actualbudget
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: actualbudget
spec:
  replicas: 1
  selector:
    matchLabels:
      app: actualbudget
  template:
    metadata:
      labels:
        app: actualbudget
    spec:
      hostname: actualbudget
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: actualbudget
          image: ghcr.io/actualbudget/actual:26.7.0-alpine
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          ports:
            - containerPort: 5006
          volumeMounts:
            - name: actualbudget-data
              mountPath: /data
          imagePullPolicy: Always
      volumes:
        - name: actualbudget-data
          persistentVolumeClaim:
            claimName: actualbudget-data-pvc