version: 2
updates:
  - package-ecosystem: "github-actions"
    open-pull-requests-limit: 1000
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directories:
      - "/ka1/kube1/services/actualbudget"
      - "/ka1/kube1/services/homeassistant"
      - "/ka1/kube1/services/kanidm"
      - "/ka1/kube1/services/leantime"
      - "/ka1/kube1/services/mosquitto"
      - "/ka1/kube1/services/openwebui"
      - "/ka1/kube1/services/plex"
      - "/ka1/kube1/services/vikunja"
      - "/ka1/kube1/services/wealthfolio"
      - "/ka1/kube1/services/zigbee2mqtt"
    open-pull-requests-limit: 1000
    schedule:
      interval: "cron"
      cronjob: "0 3 * * *"
