apiVersion: v1
kind: ServiceAccount
metadata:
  name: mosquitto-sa 
  annotation:
    eks.amazonaws.com/role-arn: arn:aws:iam::891920435804:role/ka1-k8s-secrets-readonly
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: mosquitto-secretstore
spec:
  provider:
    aws:
      service: ParameterStore
      region: eu-central-1
      auth:
        jwt:
          serviceAccountRef:
            name: mosquitto-sa
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto-tcp-ingress
spec:
  type: LoadBalancer
  loadBalancerIP: 10.10.41.252
  ports:
    - name: mosquitto
      port: 1883
      targetPort: 1883
  selector:
    app: mosquitto
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: externalsecret-mosquitto-passwd
spec:
  refreshPolicy: CreatedOnce
  secretStoreRef:
    name: mosquitto-secretstore
    kind: SecretStore
  target:
    name: secret-mosquitto-passwd
  data:
    - secretKey: file
      remoteRef:
        key: /ka1/mosquitto/passwd
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
data:
  mosquitto.conf: |
    listener 1883
    allow_anonymous false
    persistence true
    persistence_location /mosquitto/data/
    password_file /mosquitto/config/passwd
    log_dest file /mosquitto/log/mosquitto.log
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      hostname: mosquitto
      containers:
        - name: mosquitto
          image: eclipse-mosquitto:2.0.22-openssl
          ports:
            - containerPort: 1883
          volumeMounts:
            - name: mosquitto-config
              mountPath: /mosquitto/config/mosquitto.conf
              subPath: mosquitto.conf
            - name: mosquitto-passwd
              mountPath: /mosquitto/config/passwd
              subPath: passwd
            - name: mosquitto-data
              mountPath: /mosquitto/data
          imagePullPolicy: Always
      volumes:
        - name: mosquitto-config
          configMap:
            name: mosquitto-config
        - name: mosquitto-passwd
          secret:
            secretName: secret-mosquitto-passwd
            items:
              - key: file
                path: passwd
        - name: mosquitto-data
          persistentVolumeClaim:
            claimName: mosquitto-data-pvc