apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: z2m-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: z2m
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: z2m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: z2m
spec:
  replicas: 1
  selector:
    matchLabels:
      app: z2m
  template:
    metadata:
      labels:
        app: z2m
    spec:
      hostname: z2m
      containers:
        - name: z2m
          image: ghcr.io/koenkk/zigbee2mqtt:2.7.1
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: z2m-data
              mountPath: /app/data
          imagePullPolicy: Always
      volumes:
        - name: z2m-data
          persistentVolumeClaim:
            claimName: z2m-data-pvc