apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kanidm-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: kanidm-ingress
  labels:
    lb-pool: reserved
spec:
  type: LoadBalancer
  loadBalancerIP: 10.10.41.251
  ports:
    - name: kanidm
      port: 8443
      targetPort: 8443
  selector:
    app: kanidm
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kanidm-config
data:
  server.toml: |
    version = "2"
    bindaddress = "0.0.0.0:8443"

    db_path = "/db/kanidm.db"

    tls_chain = "/var/lib/kanidm/tls.crt"
    tls_key = "/var/lib/kanidm/tls.key"

    domain = "brodatzki.id"
    origin = "https://brodatzki.id"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kanidm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kanidm
  template:
    metadata:
      labels:
        app: kanidm
    spec:
      hostname: kanidm
      containers:
        - name: kanidm
          image: docker.io/kanidm/server:1.10.4
          ports:
            - containerPort: 8443
          volumeMounts:
            - name: kanidm-data
              mountPath: /db
            - name: kanidm-config
              mountPath: /data
            - name: kanidm-certs
              mountPath: /var/lib/kanidm
              readOnly: true
          imagePullPolicy: Always
      volumes:
        - name: kanidm-data
          persistentVolumeClaim:
            claimName: kanidm-data-pvc
        - name: kanidm-config
          configMap:
            name: kanidm-config
        - name: kanidm-certs
          secret:
            secretName: kanidm-gateway-tls
