apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kanidm-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: kanidm
spec:
  type: ClusterIP
  ports:
    - name: kanidm
      port: 8443
      targetPort: 8443
  selector:
    app: kanidm
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kanidm-config
data:
  server.toml: |
    version = "2"

    bindaddress = "0.0.0.0:8443"

    db_path = "/data/kanidm.db"

    tls_chain = "/var/lib/kanidm/tls.crt"
    tls_key = "/var/lib/kanidm/tls.key"

    domain = "brodatzki.id"
    origin = "https://brodatzki.id"
  
    [replication]
    origin = "repl://ka1.brodatzki.id:8444"
    bindaddress = "127.0.0.1:8444"

    [replication."repl://core.brodatzki.id:8444"]
    type = "pull"
    supplier_cert = "MIIB2TCCAX-gAwIBAgIRAaSKMJqJHEjQm4kt9tsSnDwwCgYIKoZIzj0EAwIwTDEtMCsGA1UEAwwkYTQ4YTMwOWEtODkxYy00OGQwLTliODktMmRmNmRiMTI5YzNjMRswGQYDVQQKDBJLYW5pZG0gUmVwbGljYXRpb24wHhcNMjYwNzAzMTc1ODE2WhcNMzAwNzAzMTc1ODE2WjBMMS0wKwYDVQQDDCRhNDhhMzA5YS04OTFjLTQ4ZDAtOWI4OS0yZGY2ZGIxMjljM2MxGzAZBgNVBAoMEkthbmlkbSBSZXBsaWNhdGlvbjBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABIqzqGgU4ZeXwd-nO0JT3IUrk5nKLQmC7juGwFfSzSi4FLLV3EEMxItaV8E5FMXDAYS4-fjFbghuyQ-HQ1eUwdyjQjBAMCAGA1UdJQEB_wQWMBQGCCsGAQUFBwMCBggrBgEFBQcDATAcBgNVHREEFTATghFjb3JlLmJyb2RhdHpraS5pZDAKBggqhkjOPQQDAgNIADBFAiEAzxAPPqaFtmnBQZd_kdqdnEZ2roKk112aXImMLxvjklcCIDyv2B_9CbnRAVJgMLF89DqRlpb7vvv4w6zTbQMmob6O"
    automatic_refresh = true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kanidm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kanidm
  template:
    metadata:
      labels:
        app: kanidm
    spec:
      hostname: kanidm
      containers:
        - name: kanidm
          image: docker.io/kanidm/server:1.10.4
          ports:
            - containerPort: 8443
          volumeMounts:
            - name: kanidm-data
              mountPath: /data
            - name: kanidm-config
              subPath: server.toml
              mountPath: /data/server.toml
              readOnly: true
            - name: kanidm-certs
              mountPath: /var/lib/kanidm
              readOnly: true
          imagePullPolicy: Always
      volumes:
        - name: kanidm-data
          persistentVolumeClaim:
            claimName: kanidm-data-pvc
        - name: kanidm-config
          configMap:
            name: kanidm-config
        - name: kanidm-certs
          secret:
            secretName: kanidm-gateway-tls
