apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 32Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-audio-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: Service
metadata:
  name: plex
spec:
  type: ClusterIP
  ports:
    - port: 32400
      targetPort: 32400
  selector:
    app: plex
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      containers:
        - name: plex
          image: linuxserver/plex:1.43.0
          ports:
            - containerPort: 32400
          volumeMounts:
            - name: plex-config
              mountPath: /config
            - name: plex-audio
              mountPath: /media/audio
          env:
            - name: TZ
              value: Europe/Berlin
          imagePullPolicy: Always
      volumes:
        - name: plex-config
          persistentVolumeClaim:
            claimName: plex-config-pvc
        - name: plex-audio
          persistentVolumeClaim:
            claimName: plex-audio-pvc

