apiVersion: v1
kind: Service
metadata:
  name: paperless-gotenberg
spec:
  ports:
    - port: 3000
  selector:
    app: paperless-gotenberg
  clusterIP: None
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-paperless-to-gotenberg
spec:
  podSelector:
    matchLabels:
      app: paperless-gotenberg
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: paperless-paperless
      ports:
        - protocol: TCP
          port: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: paperless-gotenberg
spec:
  selector:
    matchLabels:
      app: paperless-gotenberg
  template:
    metadata:
      labels:
        app: paperless-gotenberg
    spec:
      hostname: paperless-gotenberg
      containers:
        - name: paperless-gotenberg
          image: docker.io/gotenberg/gotenberg:8.25
          command: ['gotenberg']
          args:
            - "--chromium-disable-javascript=true"
            - "--chromium-allow-list=file:///tmp/.*"
