apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassistant-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 32Gi
---
apiVersion: v1
kind: Service
metadata:
  name: homeassistant
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8123
      targetPort: 8123
  selector:
    app: homeassistant
---
apiVersion: v1
kind: Service
metadata:
  name: homeassistant-tcp-ingress
spec:
  type: LoadBalancer
  loadBalancerIP: 10.10.41.253
  ports:
    - name: sonos
      port: 1400
      targetPort: 1400
  selector:
    app: homeassistant
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeassistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      containers:
        - name: homeassistant
          image: ghcr.io/home-assistant/home-assistant:2026.4.1
          ports:
            - containerPort: 8123
            - containerPort: 1400
          volumeMounts:
            - name: homeassistant-config
              mountPath: /config
            - name: homeassistant-config-configuration
              mountPath: /config/configuration.yaml
              subPath: configuration.yaml
            - name: homeassistant-config-configuration
              mountPath: /config/sonos.yaml
              subPath: sonos.yaml
          env:
            - name: TZ
              value: Europe/Berlin
          imagePullPolicy: Always
      volumes:
        - name: homeassistant-config
          persistentVolumeClaim:
            claimName: homeassistant-config-pvc
        - name: homeassistant-config-configuration
          configMap:
            name: homeassistant-config
