apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: externalsecret-openwebui-cnpg
spec:
  refreshPolicy: CreatedOnce
  secretStoreRef:
    name: openwebui-secretstore
    kind: SecretStore
  target:
    name: secret-openwebui-cnpg
  data:
    - secretKey: ACCESS_KEY_ID
      remoteRef:
        key: /ka1/openwebui/cnpg/key_id
    - secretKey: ACCESS_SECRET_KEY
      remoteRef:
        key: /ka1/openwebui/cnpg/secret_key
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-openwebui
spec:
  instances: 1
  storage:
    size: 16Gi
  bootsrap:
    recovery:
      source: cluster-openwebui-backup
  backup:
    retentionPolicy: '14d'
    barmanObjectStore:
        destinationPath: s3://brodatzkinet-ka1/cnpg/openwebui-20260712-2
        endpointURL: https://s3.eu-central-003.backblazeb2.com
        s3Credentials:
          accessKeyId:
            name: secret-openwebui-cnpg
            key: ACCESS_KEY_ID
          secretAccessKey:
            name: secret-openwebui-cnpg
            key: ACCESS_SECRET_KEY
        wal:
          compression: gzip
        data:
          compression: gzip
  externalClusters:
  - name: cluster-openwebui-backup
    barmanObjectStore:
      serverName: cluster-openwebui
      destinationPath: s3://brodatzkinet-ka1/cnpg/.restore/openwebui
      endpointURL: https://s3.eu-central-003.backblazeb2.com
      s3Credentials:
        accessKeyId:
          name: secret-openwebui-cnpg
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: secret-openwebui-cnpg
          key: ACCESS_SECRET_KEY
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: cluster-openwebui-daily
spec:
  schedule: '0 0 3 * * *'
  backupOwnerReference: self
  cluster:
    name: cluster-openwebui
