apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openwebui
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: default
  sources:
    - chart: open-webui
      repoURL: https://open-webui.github.io/helm-charts
      targetRevision: v0.10.1
      helm:
        values: |
          ollama:
            enabled: false
          route:
            enabled: true
            annotations:
              cert-manager.io/cluster-issuer: "clusterissuer-cloudflare-acme-prod"
            hostnames:
              - openwebui.ka1.brodatzki.net
            parentRefs:
              - openwebui-https-gateway
          persistence:
            storageClass: longhorn
  destination:
    server: https://kubernetes.default.svc
    namespace: openwebui