apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-manager-secrets-sa
  namespace: cert-manager
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::891920435804:role/ka1-k8s-secrets-readonly
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: cert-manager-secretstore
  namespace: cert-manager
spec:
  provider:
    aws:
      service: ParameterStore
      region: eu-central-1
      auth:
        jwt:
          serviceAccountRef:
            name: cert-manager-secrets-sa
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: externalsecret-cloudflare-acme-api-token
  namespace: cert-manager
spec:
  refreshPolicy: CreatedOnce
  secretStoreRef:
    name: cert-manager-secretstore
    kind: SecretStore
  target:
    name: secret-cloudflare-acme
  data:
    - secretKey: api-token
      remoteRef:
          key: /ka1/cloudflare/acme_api_token
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: clusterissuer-cloudflare-acme-prod
  namespace: cert-manager
spec:
  acme:
    email: admin+acme@brodatzki.net
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: secret-clusterissuer-cloudflare-account-key
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: secret-cloudflare-acme
            key: api-token

